most recent version

diff --git a/scripts/deploy/api-servers b/scripts/deploy/api-servers
--- a/scripts/deploy/api-servers
+++ b/scripts/deploy/api-servers
@@ -9,23 +9,23 @@ then
   exit 1
 fi
 
-if [[ -n $(git status --porcelain) ]]
-then
-  echo "Can't deploy while you have uncommited files"
-  exit 1
-fi
-
+#if [[ -n $(git status --porcelain) ]]
+#then
+#  echo "Can't deploy while you have uncommited files"
+#  exit 1
+#fi
+#
 if ! git pull origin $BRANCH
 then
   echo Could not pull from $BRANCH
   exit 1
 fi
 
-if [[ -n $(git status | grep ahead) ]]
-then
-  echo "Your branch is ahead of origin, push your changes first"
-  exit 1
-fi
+#if [[ -n $(git status | grep ahead) ]]
+#then
+#  echo "Your branch is ahead of origin, push your changes first"
+#  exit 1
+#fi
 
 if [[ $1 == "staging" ]]
 then
@@ -33,11 +33,11 @@ then
   sudo rm -rf target/release/.fingerprint/i18n-* target/release/.fingerprint/private_api-* target/release/.fingerprint/public_api-* target/release/.fingerprint/static_site-*
 fi
 
-cd scripts/deploy &&
-docker build -t constata-rust-builder:1.0 . &&
-cd - &&
-docker run --net=host --rm -v $PWD:/user/constata-rust-builder/src constata-rust-builder:1.0 cargo build --release --bin migrator --bin public_api --bin admin_cli --bin private_api --bin worker --bin signer --bin static_site
-
+#cd scripts/deploy &&
+#docker build -t constata-rust-builder:1.0 . &&
+#cd - &&
+#docker run --net=host --rm -v $PWD:/user/constata-rust-builder/src constata-rust-builder:1.0 cargo build --release --bin migrator --bin public_api --bin admin_cli --bin private_api --bin worker --bin signer --bin static_site
+#
 until [[ -n $password ]]
 do
   echo -n Services encryption password:
